server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://ep-solitary-frog-a283lfjt-pooler.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_ZXca5D2COgIr&sslmode=require
    username: neondb_owner
    password: npg_ZXca5D2COgIr
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
